import { GamesSharp } from '@vicons/material';
import { defineTool } from '../tool';
import { translate } from '@/plugins/i18n.plugin';

export const games = [
  defineTool({
    path: '/2048',
    name: translate('tools.2048.title', [], '摸鱼2048'),
    description: translate('tools.2048.description', [], '摸鱼2048在线小游戏'),
    keywords: ['小游戏', 'gaming'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/2048/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/happy2048',
    name: translate('tools.happy2048.title', [], '快乐2048'),
    description: translate('tools.happy2048.description', [], '超级解压的 2048 小游戏：把相同的两个方块数字移动到一起生成更高的数字，就可以获得相应的分数'),
    keywords: ['小游戏', 'gaming'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/1415072749/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/sudoku-raravi',
    name: translate('tools.sudoku-raravi.title', [], '数独游戏2'),
    description: translate('tools.sudoku-raravi.description', [], '又一个在线网页版的数独游戏'),
    keywords: ['小游戏', 'gaming', '数独游戏2'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/x/games/sudoku-raravi/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/TangramBlocks',
    name: translate('tools.TangramBlocks.title', [], '七巧板'),
    description: translate('tools.TangramBlocks.description', [], 'Tangram Blocks，一个在线益智小游戏'),
    keywords: ['小游戏', 'gaming', 'Tangram Blocks'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/TangramBlocks/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/sudoku',
    name: translate('tools.sudoku.title', [], '数独游戏'),
    description: translate('tools.sudoku.description', [], '简洁的在线数独游戏'),
    keywords: ['小游戏', 'gaming', '数独游戏'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/x/games/sudoku/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/0919466540',
    name: translate('tools.0919466540.title', [], '豆娃垃圾分类'),
    description: translate('tools.0919466540.description', [], '小朋友们，垃圾分类是一项重要的环保意识哦，每个人都要学会垃圾分类，共同爱护好我们的环境。现在让我们一起来和豆娃学习如何进行垃圾分类吧，看谁做的最棒！'),
    keywords: ['小游戏', 'gaming', '豆娃垃圾分类'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/0919466540/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/1514486813',
    name: translate('tools.1514486813.title', [], '火箭飞行器'),
    description: translate('tools.1514486813.description', [], 'Rocket Flight，火箭飞行器'),
    keywords: ['小游戏', 'gaming', '火箭飞行器'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/1514486813/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/1519486693',
    name: translate('tools.1519486693.title', [], '滚筒喷射'),
    description: translate('tools.1519486693.description', [], '滚筒喷射(Paint Blue GD)是一款非常容易上瘾的趣味性游戏，在这款游戏中玩家需要控制一颗会不断掉色的小球，控制其滚动的方向，在最短的时间将整个空间充满油漆，随着关卡的提升， 难度也会增加'),
    keywords: ['小游戏', 'gaming', '滚筒喷射'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/1519486693/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/games',
    name: translate('tools.games.title', [], 'h5小游戏集合'),
    description: translate('tools.games.description', [], '收集的好玩又解压的 h5 在线小游戏'),
    keywords: ['小游戏', 'gaming', 'h5小游戏集合'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/ttxg',
    name: translate('tools.ttxg.title', [], '弹跳小怪'),
    description: translate('tools.ttxg.description', [], '这是一款非常好玩的敏捷小游戏，游戏中你需要准确的控制小怪去跳跃，躲避所有的障碍物，吃掉所有的星星游戏即可胜利。'),
    keywords: ['小游戏', 'gaming', '弹跳小怪'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/ttxg',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/0955243594',
    name: translate('tools.0955243594.title', [], '音乐之路3'),
    description: translate('tools.0955243594.description', [], '音乐之路3全新上线。全新模式，增加了黑夜的闯关模式。还增加了炫酷的皮肤，道具各种玩法，另外游戏中增加了段位水平，欢迎大家前来挑战。'),
    keywords: ['小游戏', 'gaming', '音乐之路3'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/0955243594/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
  defineTool({
    path: '/Tronix',
    name: translate('tools.Tronix.title', [], '点和线2(Tronix II)'),
    description: translate('tools.Tronix.description', [], '点和线是一款有趣的益智类游戏，利用这些排列图形的点和线，移动点的位置，让点和线不接触任何其他线，并组成出一个个图形，游戏一开始很容易，但是会变得越来越难，现在是时候用你的大脑来挑战这些关卡了！'),
    keywords: ['小游戏', 'gaming', '点和线2(Tronix II)'],
    component: () => import('./frame-loader.vue'),
    icon: GamesSharp,
    config: {
      remoteUrl: 'https://lzw.me/pages/games/Tronix/',
      hideHeader: true,
    },
    category: 'gaming',
    createdAt: new Date('2025-11-30'),
  }),
];
